### ISSUE TITLE
who command causing out of index error

### ISSUE THREAD

**Issue by pastaq** [ShadowBlip/HandyGCCS#52]
After GPD WinMax2 support was added, a bug was noted when starting the service at boot time on some devices. This has been observed on the OneXPlayer Mini AMD and the AOK ZOE A1

```
Nov 25 20:00:32 chimeraos systemd[1]: Started Handheld Game Console Controller Service.
Nov 25 20:00:32 chimeraos python3[485]: Traceback (most recent call last):
Nov 25 20:00:32 chimeraos python3[485]:   File "/usr/local/bin/handycon.py", line 65, in <module>
Nov 25 20:00:32 chimeraos python3[485]:     who = [(w[0], re.search(r"(\d{4}-\d{2}-\d{2}\s\d{2}:\d{2})", w[1]).groups()[0]) for w in who]
Nov 25 20:00:32 chimeraos python3[485]:   File "/usr/local/bin/handycon.py", line 65, in <listcomp>
Nov 25 20:00:32 chimeraos python3[485]:     who = [(w[0], re.search(r"(\d{4}-\d{2}-\d{2}\s\d{2}:\d{2})", w[1]).groups()[0]) for w in who]
Nov 25 20:00:32 chimeraos python3[485]: IndexError: list index out of range
Nov 25 20:00:32 chimeraos systemd[1]: handycon.service: Main process exited, code=exited, status=1/FAILURE
Nov 25 20:00:32 chimeraos systemd[1]: handycon.service: Failed with result 'exit-code'.
```

**Comment by pastaq** [comment]
I'll be reverting this part of the code for stability until a revised approach can be verified stable.
